title: sketch-a-day
email: awdriggs@gmail.com
description: a p5 sketch every day
baseurl: "/sketchaday"  # Change to your actual repository name
url: "https://awdriggs.github.io"  # Your GitHub Pages domain
github_username: awdriggs

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

include:
  - assets
  - sketches

paginate: 42
paginate_path: "/page:num/"

permalink: /:title.html
